# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tatakelola', '0002_auto_20170331_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kebijakan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risiko_proyek', models.TextField()),
                ('risiko_informasi', models.TextField()),
                ('risiko_keberlangsungan_layanan', models.TextField()),
                ('implementasi_project_governance', models.TextField()),
                ('implementasi_security_goernance', models.TextField()),
                ('sumber_dana', models.TextField()),
                ('penganggaran_modal', models.TextField()),
                ('prosedur_pengadaan', models.TextField()),
                ('prioritas_anggaran', models.TextField()),
                ('perhitungan_manfaat_biaya', models.TextField()),
                ('efisiensi_finansial', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('proyek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tatakelola.Proyek')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField()),
                ('mekanisme_internal', models.TextField()),
                ('mekanisme_eksternal', models.TextField()),
            ],
        ),
    ]
