# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-06 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tatakelola', '0007_auto_20170406_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
