# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-17 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatakelola', '0010_proyek_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='NIP',
            field=models.CharField(max_length=18),
        ),
    ]
