# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-18 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tatakelola', '0013_auto_20170418_0252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monitor',
            new_name='EvaluasidanMonitor',
        ),
    ]
