# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatakelola', '0014_auto_20170418_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyek',
            name='status',
            field=models.CharField(choices=[('T', 'Diterima'), ('DT', 'Ditolak')], max_length=9),
        ),
    ]
