# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatakelola', '0016_auto_20170425_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyek',
            name='latest_step',
            field=models.CharField(choices=[('PS', 'Perencanaan Sistem'), ('MB', 'Manajemen Belanja'), ('RS', 'Realisasi Sistem'), ('OS', 'Pengoperasian Sistem'), ('MS', 'Pemeliharaan Sistem')], max_length=32),
        ),
    ]
