# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatakelola', '0017_auto_20170425_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyek',
            name='status',
            field=models.CharField(choices=[('Diterima', 'T'), ('DT', 'Ditolak')], max_length=9),
        ),
    ]
