# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-04 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tatakelola', '0019_auto_20170425_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kebijakan',
            name='proyek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tatakelola.Proyek'),
        ),
    ]
